package com.cde.sdk.auth

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Holds the session token between launches, encrypted at rest.
 *
 * A bearer token is a credential: in plain preferences it is readable on a
 * rooted device and lands in unencrypted backups. Values here are sealed with
 * an AES-256-GCM key held in the Android keystore, so the key material never
 * enters the app's process and a copied preferences file is inert on any other
 * device.
 *
 * This used to delegate to `androidx.security:security-crypto`, which Google
 * deprecated in April 2025 in favour of using the keystore directly. Doing
 * that here also keeps the SDK free of a dependency host apps would otherwise
 * inherit — and of one that is no longer receiving fixes.
 */
class TokenStore(context: Context) {

    private val preferences: SharedPreferences =
        context.getSharedPreferences(PREFERENCES_FILE, Context.MODE_PRIVATE)

    val token: String? get() = read(KEY_TOKEN)
    val username: String? get() = read(KEY_USERNAME)
    val role: String? get() = read(KEY_ROLE)

    @Synchronized
    fun store(token: String, username: String, role: String) {
        val editor = preferences.edit()
        for ((key, value) in listOf(
            KEY_TOKEN to token, KEY_USERNAME to username, KEY_ROLE to role,
        )) {
            val sealed = seal(value)
            // Failing to encrypt must not silently fall back to plaintext.
            // Storing nothing costs a sign-in; storing it in the clear is a
            // credential leak the caller would never learn about.
            if (sealed == null) {
                editor.remove(key)
            } else {
                editor.putString(key, sealed)
            }
        }
        editor.apply()
    }

    @Synchronized
    fun clear() {
        preferences.edit().clear().apply()
    }

    // ── Encryption ───────────────────────────────────────────────

    @Synchronized
    private fun read(key: String): String? {
        val stored = preferences.getString(key, null) ?: return null
        return unseal(stored) ?: run {
            // The key is gone or no longer usable — a restore onto a new
            // device, or a keystore reset. The stored bytes can never be read
            // again, so drop them and let the caller sign in rather than
            // retrying a decryption that cannot succeed.
            clear()
            null
        }
    }

    private fun seal(value: String): String? = runCatching {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        // The IV is generated by the cipher, never chosen here. Reusing one
        // with the same GCM key would leak the plaintext outright.
        val iv = cipher.iv
        val ciphertext = cipher.doFinal(value.toByteArray(Charsets.UTF_8))
        Base64.encodeToString(iv + ciphertext, Base64.NO_WRAP)
    }.getOrNull()

    private fun unseal(stored: String): String? = runCatching {
        val bytes = Base64.decode(stored, Base64.NO_WRAP)
        if (bytes.size <= IV_LENGTH) return@runCatching null
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            secretKey(),
            GCMParameterSpec(TAG_LENGTH_BITS, bytes, 0, IV_LENGTH),
        )
        String(
            cipher.doFinal(bytes, IV_LENGTH, bytes.size - IV_LENGTH),
            Charsets.UTF_8,
        )
    }.getOrNull()

    /** The keystore key, created on first use and reused thereafter. */
    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)
            ?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                // Deliberately not requiring user authentication: queued markup
                // syncs in the background while the phone is in a pocket, and
                // that request needs the token. The keystore still binds the
                // key to this device.
                .setUserAuthenticationRequired(false)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "cde-sdk-session"
        const val PREFERENCES_FILE = "cde-sdk-session"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_SIZE_BITS = 256
        const val TAG_LENGTH_BITS = 128
        /** GCM standard nonce length. */
        const val IV_LENGTH = 12

        const val KEY_TOKEN = "token"
        const val KEY_USERNAME = "username"
        const val KEY_ROLE = "role"
    }
}
