#!/usr/bin/env bash
# Regenerate requirements.txt (the full pinned closure) from requirements.in
# (the direct dependencies).
#
#   ./lock-requirements.sh            regenerate in place
#   ./lock-requirements.sh --check    fail if the committed file is stale
#
# Uses only pip's own resolver via `--dry-run --report`, so there is no
# pip-tools/uv to install and no second resolver whose answer could differ
# from the one Docker will actually get.
#
# Why versions and not hashes: pip's --require-hashes needs every acceptable
# artifact's hash, and wheels are per-platform. ifcopenshell ships
# manylinux_2_31 for x86_64 and aarch64 as separate files, so a hash list
# generated on one architecture silently refuses to install on the other —
# the converter image would become amd64-only without anyone deciding that.
# PyPI already refuses to re-upload a different file for a (name, version,
# filename) triple, so an exact version pin fixes the bytes anyway; the hash
# would add protection only against PyPI itself being compromised, at the
# cost of an architecture lock-in we do not want.
set -euo pipefail

cd "$(dirname "$0")"

IN=requirements.in
OUT=requirements.txt
DEV_IN=requirements-dev.in
DEV_OUT=requirements-dev.txt

# The interpreter must be the one the image will run, because pip resolves
# against the *running* Python. This is not pedantry: numpy 2.5 requires
# >=3.12, so resolving on 3.11 pins numpy 2.4 while the ubuntu:24.04 image
# installs 2.5 — a lockfile that disagrees with the thing it locks, and
# nothing would have said so.
#
# Tied to the `FROM ubuntu:24.04` stages in Dockerfile, which ship 3.12.
# Change both together or the venv copied between stages will not import.
REQUIRED_PYTHON_MINOR=12

PYTHON="${PYTHON:-}"
if [[ -z "$PYTHON" ]]; then
    if command -v "python3.${REQUIRED_PYTHON_MINOR}" >/dev/null; then
        PYTHON="python3.${REQUIRED_PYTHON_MINOR}"
    else
        PYTHON=python3
    fi
fi
command -v "$PYTHON" >/dev/null || { echo "$PYTHON not found" >&2; exit 1; }

actual_minor=$("$PYTHON" -c 'import sys; print(sys.version_info.minor)')
if [[ "$actual_minor" != "$REQUIRED_PYTHON_MINOR" ]]; then
    cat >&2 <<MSG
$PYTHON is Python 3.$actual_minor, but the converter image runs 3.$REQUIRED_PYTHON_MINOR.

pip resolves against the running interpreter, so a lock written here would
pin versions the image will not install. Install python3.$REQUIRED_PYTHON_MINOR, or point at it:

    PYTHON=/path/to/python3.$REQUIRED_PYTHON_MINOR $0 ${1:-}
MSG
    exit 1
fi

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# The generator is one script used for both files. requirements-dev.in starts
# with `-r requirements.in`, so its resolution contains the production closure
# too; passing the production .in as the exclude list keeps the dev file to
# the packages that are genuinely test-only, and leaves the shared ones with
# exactly one pin, in requirements.txt.
cat > "$work/render.py" <<'PY'
import json, re, sys

report_path, in_path, exclude_path = sys.argv[1], sys.argv[2], sys.argv[3]
report = json.load(open(report_path))


def canonical(name):
    """PEP 503 normalisation, so `Pillow` and `pillow` are one package."""
    return re.sub(r"[-_.]+", "-", name).lower()


def declared_in(path):
    names = set()
    for line in open(path):
        line = line.split("#", 1)[0].strip()
        if not line or line.startswith("-"):      # skip `-r other.in`
            continue
        names.add(canonical(re.split(r"[\[<>=!~;\s]", line)[0]))
    return names


direct = declared_in(in_path)

resolved = {}
for entry in report["install"]:
    meta = entry["metadata"]
    resolved[canonical(meta["name"])] = (meta["name"], meta["version"])

missing = direct - resolved.keys()
if missing:
    sys.exit(f"resolver did not return direct requirement(s): {sorted(missing)}")

if exclude_path:
    # Everything the production lock already pins, transitives included: it is
    # resolved separately and re-pinning it here would let the two files
    # disagree about the same package.
    prod_report = json.load(open(report_path + ".prod"))
    already = {canonical(e["metadata"]["name"]) for e in prod_report["install"]}
    resolved = {k: v for k, v in resolved.items() if k not in already}
    direct &= resolved.keys()

print("# GENERATED by lock-requirements.sh — do not edit by hand.")
print(f"# Edit {in_path.replace('.txt', '.in')} and re-run ./lock-requirements.sh.")
print("#")
if exclude_path:
    print("# Test-only. The production closure is included by reference below")
    print("# rather than duplicated, so a shared package has exactly one pin.")
else:
    print("# The full closure is pinned, transitive dependencies included, so the")
    print("# image built today and the image built in six months install the same")
    print("# code. An unpinned transitive dependency is still an unpinned")
    print("# dependency: it is simply one nobody reads.")
print()
if exclude_path:
    print("-r requirements.txt")
    print()
print("# ── Direct ────────────────────────────────────────────────────")
for key in sorted(direct):
    name, version = resolved[key]
    print(f"{name}=={version}")
transitive = sorted(resolved.keys() - direct)
if transitive:
    print()
    print("# ── Transitive (pulled in by the above) ───────────────────────")
    for key in transitive:
        name, version = resolved[key]
        print(f"{name}=={version}")
PY

resolve_into() {  # <in> <report-name>
    "$PYTHON" -m pip install --dry-run --ignore-installed --quiet \
        --report "$work/$2" -r "$1" >&2
}

echo "Resolving $IN with $PYTHON (3.$actual_minor) ..." >&2
resolve_into "$IN" prod.json
"$PYTHON" "$work/render.py" "$work/prod.json" "$IN" "" > "$work/$OUT"

echo "Resolving $DEV_IN ..." >&2
resolve_into "$DEV_IN" dev.json
cp "$work/prod.json" "$work/dev.json.prod"
"$PYTHON" "$work/render.py" "$work/dev.json" "$DEV_IN" "$IN" > "$work/$DEV_OUT"

stale=0
compare() {  # <committed> <generated>
    if ! diff -u "$1" "$work/$1" > "$work/diff.$1" 2>&1; then
        cat "$work/diff.$1" >&2
        stale=1
    fi
}

if [[ "${1:-}" == "--check" ]]; then
    compare "$OUT"
    compare "$DEV_OUT"
    if (( stale )); then
        cat >&2 <<'MSG'

A pinned file does not match its .in.

Run converter/lock-requirements.sh and commit the result. A pinned file that
has drifted from its input is worse than no pin: it reads as deliberate.
MSG
        exit 1
    fi
    echo "$OUT and $DEV_OUT are up to date." >&2
else
    mv "$work/$OUT" "$OUT"
    mv "$work/$DEV_OUT" "$DEV_OUT"
    echo "Wrote $OUT ($(grep -cE '==' "$OUT") pins) and $DEV_OUT ($(grep -cE '==' "$DEV_OUT") pins)." >&2
fi
