-- Baseline schema.
--
-- Generated by letting Hibernate build the schema against PostgreSQL 17 and
-- dumping the result, then reordering it for reading and naming the
-- constraints. Types match what Hibernate expects exactly, because
-- ddl-auto is now `validate`: a column that differs here fails startup
-- rather than being quietly corrected at runtime.
--
-- Referential behaviour is left as Hibernate generated it — no ON DELETE
-- CASCADE. Deletion is handled by JPA cascades in the entity graph, and
-- adding a second, database-level cascade would remove rows the application
-- never asked to remove.

-- ── Users ────────────────────────────────────────────────────────
CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   varchar(255) NOT NULL,
    email      varchar(255) NOT NULL,
    password   varchar(255) NOT NULL,
    role       varchar(255),
    created_at timestamp(6),

    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email),
    CONSTRAINT users_role_check  CHECK (role IN ('ADMIN', 'ENGINEER', 'REVIEWER', 'VIEWER'))
);

-- ── Projects ─────────────────────────────────────────────────────
CREATE TABLE projects (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL,
    description varchar(255),
    location    varchar(255),
    phase       varchar(255),
    owner_id    bigint,
    created_at  timestamp(6),
    updated_at  timestamp(6),

    CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT projects_phase_check
        CHECK (phase IN ('CONCEPT', 'DESIGN', 'CONSTRUCTION', 'HANDOVER', 'OPERATION'))
);

-- ── Documents ────────────────────────────────────────────────────
CREATE TABLE documents (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255) NOT NULL,
    description     varchar(255),
    file_name       varchar(255),
    file_path       varchar(255),
    file_type       varchar(255),
    file_size       bigint,
    current_version integer,
    document_type   varchar(255),
    status          varchar(255),
    revision        varchar(255),
    drawing_number  varchar(255),
    sheet_number    varchar(255),
    -- Converted SVG for a drawing. Large, and read only when the document is
    -- opened, so text rather than a bounded varchar.
    vector_data     text,
    project_id      bigint,
    uploaded_by     bigint,
    created_at      timestamp(6),
    updated_at      timestamp(6),

    CONSTRAINT fk_documents_project     FOREIGN KEY (project_id)  REFERENCES projects (id),
    CONSTRAINT fk_documents_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id),
    CONSTRAINT documents_document_type_check
        CHECK (document_type IN ('DRAWING', 'SPECIFICATION', 'REPORT', 'SCHEDULE',
                                 'BIM_MODEL', 'POINT_CLOUD', 'OTHER')),
    CONSTRAINT documents_status_check
        CHECK (status IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'SUPERSEDED', 'VOID'))
);

-- ── Document versions ────────────────────────────────────────────
CREATE TABLE document_versions (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id    bigint       NOT NULL,
    -- 1-based and gap-free. Version 1 is always the uploaded original.
    version_number integer      NOT NULL,
    file_name      varchar(255),
    -- Absolute path to this version's bytes. Never reused between versions.
    file_path      varchar(255) NOT NULL,
    file_size      bigint,
    operation      varchar(255) NOT NULL,
    summary        varchar(500),
    content_hash   varchar(64),
    created_by     bigint,
    created_at     timestamp(6) NOT NULL,

    CONSTRAINT fk_document_versions_document   FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT fk_document_versions_created_by FOREIGN KEY (created_by)  REFERENCES users (id),
    -- Two rows claiming the same version of the same document would make
    -- "restore version 3" ambiguous.
    CONSTRAINT uk_document_version UNIQUE (document_id, version_number),
    CONSTRAINT document_versions_operation_check
        CHECK (operation IN ('UPLOAD', 'REDACT', 'OCR', 'FLATTEN', 'FORM_FILL',
                             'FORM_DESIGN', 'PAGES', 'SIGN', 'RESTORE'))
);

-- ── Annotations ──────────────────────────────────────────────────
CREATE TABLE annotations (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL,
    author_id   bigint,
    type        varchar(255),
    -- The markup itself, as JSON. Opaque to the server: it is written and
    -- read by the viewers, and nothing here parses or validates it.
    shape_data  text   NOT NULL,
    comment     varchar(255),
    status      varchar(255),
    page_number integer,
    created_at  timestamp(6),

    CONSTRAINT fk_annotations_document FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT fk_annotations_author   FOREIGN KEY (author_id)   REFERENCES users (id),
    CONSTRAINT annotations_type_check
        CHECK (type IN ('COMMENT', 'MARKUP', 'DIMENSION', 'CLOUD', 'ARROW', 'STAMP',
                        'HIGHLIGHT', 'UNDERLINE', 'STRIKEOUT', 'SQUIGGLY')),
    CONSTRAINT annotations_status_check CHECK (status IN ('OPEN', 'RESOLVED', 'CLOSED'))
);

-- ── Annotation replies ───────────────────────────────────────────
CREATE TABLE annotation_replies (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation_id bigint NOT NULL,
    author_id     bigint,
    content       text   NOT NULL,
    created_at    timestamp(6),

    CONSTRAINT fk_annotation_replies_annotation
        FOREIGN KEY (annotation_id) REFERENCES annotations (id),
    CONSTRAINT fk_annotation_replies_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- ── Digital signatures ───────────────────────────────────────────
CREATE TABLE document_signatures (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signature_id        varchar(255) NOT NULL,
    document_id         bigint       NOT NULL,
    document_version_id bigint,
    signer_id           bigint,
    signer_name         varchar(255),
    signer_email        varchar(255),
    role                varchar(255),
    reason              varchar(255),
    location            varchar(255),
    document_hash       varchar(100),
    signature_b64       text,
    certificate_b64     text,
    algorithm           varchar(255),
    status              varchar(255),
    signed_at           timestamp(6),

    CONSTRAINT uk_document_signatures_signature_id UNIQUE (signature_id),
    CONSTRAINT fk_document_signatures_document FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT fk_document_signatures_version
        FOREIGN KEY (document_version_id) REFERENCES document_versions (id),
    CONSTRAINT fk_document_signatures_signer FOREIGN KEY (signer_id) REFERENCES users (id),
    CONSTRAINT document_signatures_status_check
        CHECK (status IN ('VALID', 'INVALID', 'TAMPERED', 'EXPIRED'))
);

-- ── Indexes ──────────────────────────────────────────────────────
--
-- PostgreSQL indexes a primary key and a unique constraint automatically. It
-- does not index a foreign key column, and Hibernate does not either — so
-- without these, "every annotation on this document" is a sequential scan of
-- the whole table, and deleting a user scans every table that references one.
CREATE INDEX idx_projects_owner ON projects (owner_id);

CREATE INDEX idx_documents_project     ON documents (project_id);
CREATE INDEX idx_documents_uploaded_by ON documents (uploaded_by);

CREATE INDEX idx_document_version_document ON document_versions (document_id);
CREATE INDEX idx_document_versions_created_by ON document_versions (created_by);

CREATE INDEX idx_annotations_document ON annotations (document_id);
CREATE INDEX idx_annotations_author   ON annotations (author_id);

CREATE INDEX idx_annotation_replies_annotation ON annotation_replies (annotation_id);
CREATE INDEX idx_annotation_replies_author     ON annotation_replies (author_id);

CREATE INDEX idx_document_signatures_document ON document_signatures (document_id);
CREATE INDEX idx_document_signatures_version  ON document_signatures (document_version_id);
CREATE INDEX idx_document_signatures_signer   ON document_signatures (signer_id);
